### ISSUE TITLE
ask_rev API information not correct when using omega-h mesh returned from pumi-pic

### ISSUE THREAD

**Issue by dhyan1272** [SCOREC/omega_h#22]
The reverse classification information returned when the full/original omega-h mesh is given as an input to the API is correct.The reverse classification information returned when the omega-h mesh returned from pumi-pic is given as an input to the API is incorrect.

**Comment by cwsmith** [comment]
@dhyan1272 Thanks for creating this.  I'm going to close it since there is already an issue in omegah that was tracking it:  https://github.com/SCOREC/omega_h/issues/21 Note, when the issue was created all we were aware of was a performance issue.  It has since evolved and is being worked on in the pumi-pic issue you linked (75).
