### ISSUE TITLE
classification in simmetrix mesh converter

### ISSUE THREAD

**Issue by cwsmith** [SCOREC/omega_h#7]
From the discussion in the TOMMS issue here: https://github.com/SCOREC/tomms/issues/17

The simmetrix -> omegah mesh converter is calling `classify_equal_order` to set the geometric model entity id and dimension:

https://github.com/SCOREC/omega_h/blob/1235d6f22479bbedbf38dbde70935ca2fbd2c9d2/src/Omega_h_meshsim.cpp#L136

`clasify_equal_order` is defined here:

https://github.com/SCOREC/omega_h/blob/1235d6f22479bbedbf38dbde70935ca2fbd2c9d2/src/Omega_h_class.cpp#L168-L190

It isn't clear if this is necessary since we are explicitly querying the classification info from simmetrix; I suspect we can just set the "class_dim" and "class_id" tags directly.

**Comment by joshia5** [comment]
@cwsmith , setting the "class_dim" and "class_id" tags directly will only work for elements and vertices, not for other entities because they are created using omegah build functions: https://github.com/SCOREC/omega_h/blob/1235d6f22479bbedbf38dbde70935ca2fbd2c9d2/src/Omega_h_meshsim.cpp#L133

I think a thorough fix would be to create omegah mesh entities while preserving mapping of ids with simmetrix mesh ents and then we can set the tags directly. This build process was implemented for mixed mesh here:https://github.com/SCOREC/omega_h/blob/d96f537666cc71cd83176ba4d6b91413eaf1c606/src/Omega_h_meshsim.cpp#L111 although iirc specific omegah functions for mixed mesh building were created for that.

**Comment by cwsmith** [comment]
This is resolved with #15 .
